#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May  6 12:08:56 2025

@author: raminder
"""
import questionary
n_of_tee=()
n_of_reagents=()
reagents=[]
tee_sizes=[250, 500, 1600]
anatomy=questionary.select(
    "What is the structure of the reactor?",
    choices=["chip", "tube", "CSTR", "fixed-bed", "hybrid"]).ask()
if anatomy =="hybrid":
    print("You're going to need to write your own experimental")
# Ask user about number of reagents
while type(n_of_reagents) != int:
    n_of_reagents=questionary.text(
        "How many reagents are being put through the flow system?").ask()
    try:
        n_of_reagents = int(n_of_reagents)
        print(f"You entered the integer: {n_of_reagents}")
    except:
        print("That's not a valid integer!")
#populate reagent table
print(n_of_reagents)
for i in range(0,n_of_reagents):
    compound=input(f"Add the IUPAC name for reagent {i+1} ")
    solvent=input(f"what solvent is {compound} dissolved in?")
    concentration=input(f"what concentration is {compound} in {solvent} made up to?")
    basic_info={"compound":compound, "solvent":solvent, "concentration":concentration}
    reagents.append(basic_info)
if anatomy == "tube":
    